[package]
name = "rust"
version = "0.1.0"
authors = ["Andreas Winter <mail@andreas-winter.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
